config/routes.rb
Rails.application.routes.draw do

  resources :qnas, only: [:new, :create]

  resources :problems, only: [:create, :destroy, :index, :new]

  resources :votes, only: [:create]

  resources :polls

  resources :forums, except: [:edit, :update]

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show]

  root 'pages#home'

  match '/privacy', to: 'pages#privacy', via: 'get'

  match '/terms', to: 'pages#terms', via: 'get'

  match '/about', to: 'pages#about', via: 'get'

  match '/guestbook', to: 'problems#index', via: 'get'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :content, presence: true

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  before_action :admin_user, except: [:index, :show]

  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @comments = @forum.comments.order('created_at DESC')

  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      flash[:success] = 'Forum was created'
      redirect_to @forum
    else
      render 'new'
    end
  end

  def destroy
  end

  private

    def forum_params
      params.require(:forum).permit(:title, :content)
    end

    def admin_user
      redirect_to (forums_url) unless current_user.admin?
    end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/index.html.erb
<% if current_user.try(:admin?) %>
  <%= link_to 'New', new_forum_path, class: 'align-right btn btn-primary btn-lg' %>
<% end %>
<h1>All forums</h1>

<hr>
<ul class="forums">
  <% @forums.each do |forum| %>
    <li>
      <h2><%= link_to forum.title, forum %></h2>
      <p><%= forum.content[0..100] + '...'%></p>
    </li>
    <hr>
  <% end %>
</ul>

app/views/forums/new.html.erb
<h1>Add a forum</h1>
<hr>
<%= form_for @forum do |f| %>
  <%= render 'shared/errors', object: @forum %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, columns: 3, class: 'form-control' %>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>
<br />
<%= link_to 'Cancel', forums_path, class: 'btn btn-default' %>

app/views/forums/show.html.erb
<h1><%= @forum.title %></h1>
<div class="contents">
  <p><%= @forum.content %></p>
</div>
<hr>
<div class="comments">
  <% if user_signed_in? %>
    <%= render 'shared/comment_form' %>
  <% end %>

  <div class="comment-display">
    <h3>Comments</h3>
    <hr>
    <ul class="comment-feed">
      <% @comments.each do |comment| %> 
        <li>
          <h4><%= comment.reply %></h4><br />
          <% if (current_user.try(:admin)) or (current_user.id == comment.user_id) %>
            <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </li>
        <hr>
      <% end %>
    </ul>
  </div>
</div>