config/routes.rb
Rails.application.routes.draw do

  resources :qnas, only: [:new, :create]

  resources :problems, only: [:create, :destroy, :index, :new]

  resources :votes, only: [:create]

  resources :polls

  resources :forums, except: [:edit, :update]

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show]

  root 'pages#home'

  match '/privacy', to: 'pages#privacy', via: 'get'

  match '/terms', to: 'pages#terms', via: 'get'

  match '/about', to: 'pages#about', via: 'get'

  match '/guestbook', to: 'problems#index', via: 'get'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :vote_options, dependent: :destroy
  validates :topic, presence: true

  accepts_nested_attributes_for :vote_options, reject_if: :all_blank, allow_destroy: true

  def normalized_votes_for(option)
    votes_summary == 0? 0 : (option.votes.count.to_f / votes_summary) * 100 
  end

  def votes_summary
    vote_options.inject(0) { |summary, option| summary + option.votes.count }
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    if @poll.save
      redirect_to @poll
      flash[:success]= 'Poll was successfully created.'
      else
        render 'new'
      end
  end


  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated'
      redirect_to @poll
    else
      render 'edit'
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    flash[:success] =  'Poll was successfully deleted.'
    redirect_to polls_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
    end
end

app/helpers/polls_helper.rb
module PollsHelper

  def visualize_votes_for(option)

    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar', style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end

  end

end

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  <%= render 'shared/errors', object: @poll %>

  <div class="form-group">
    <%= f.label :topic %>
    <%= f.text_area :topic, rows: 3, required: true, class: 'form-control' %>
  </div>
  
  <div class="panel panel-default">
    <div class="panel-heading">Options</div>
    <div class="panel-body">
      <%= f.fields_for :vote_options do |options_form| %>
        <%= render 'vote_option_fields', f: options_form %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'add option', f, :vote_options %>
      </div>
    </div>
  </div>
  
  <%= f.submit 'Submit',class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/polls/_vote_option.html.erb
<div class="form-group">
  <%= content_tag(:label) do %>
    <% unless current_user.voted_for?(@poll) %>
      <%= radio_button_tag 'vote_option[id]', option.id %>
    <% end %>
    <%= option.title %>
  <% end %>
  <%= visualize_votes_for option %>
</div>

app/views/polls/_vote_option_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, required: true, class: 'form-control' %>
  </div>

<%= link_to_remove_association "remove option", f %>
</div>

app/views/polls/_voting_form.html.erb
<%= form_tag votes_path, method: :post, remote: true, id: 'voting_form' do %>
  <%= hidden_field_tag 'poll[id]', @poll.id %>

  <%= render partial: 'polls/vote_option', collection: @poll.vote_options, as: :option %>
  
  <p><b>Total votes: <%= @poll.votes_summary %></b></p>
  
  <% if current_user.voted_for?(@poll) %>
    <p>You have already voted</p>
  <% else %>
    <%= submit_tag 'Vote', class: 'btn btn-primary btn-lg' %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<h1>Edit Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<% if current_user.try(:admin?) %>
  <%= link_to 'New Poll', new_poll_path, class: 'btn btn-lg btn-primary align-right' %>
<% end %>
<h1>Polls available</h1>
<br />
<hr>
<% @polls.each do |poll| %>
  <div class="well">
    <h2><%= poll.topic %> <small>(voted: <%= poll.votes_summary %>)</small></h2>

    <% if current_user.try(:admin?) %>
      <div class="btn-group">  
        <%= link_to 'Edit', edit_poll_path(poll), class: 'btn btn-default' %>
        <%= link_to 'Destroy', poll, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <p>  
      <% elsif current_user %>
        <%= link_to 'Vote', poll, class: 'btn btn-primary btn-lg block' %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %> to participate.
      <% end %>
    </p>
  </div>
<% end %>

app/views/polls/new.html.erb
<h1>New Poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Please vote</h1>

<h2><%= @poll.topic %></h2>

<%= render 'voting_form' %>

<script data-turbolinks-track="true">
  $(document).ready(function () {
    var voting_form = $('#voting_form');
    voting_form.validate({
      focusInvalid: false,
      errorClass: 'alert alert-warning',
      errorElement: "div",
      errorPlacement: function(error, element) { voting_form.before(error); },
      rules: {
        'vote_option[id]': {
          required: true
        }
      },
      messages: {
        'vote_option[id]': {
          required: "Please select one of the options"
        }
      }
    });
  });
</script>

<%= link_to 'Back', polls_path %>