config/routes.rb
Rails.application.routes.draw do

  resources :qnas, only: [:new, :create]

  resources :problems, only: [:create, :destroy, :index, :new]

  resources :votes, only: [:create]

  resources :polls

  resources :forums, except: [:edit, :update]

  resources :comments, only: [:create, :edit, :update, :destroy]

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:index, :show]

  root 'pages#home'

  match '/privacy', to: 'pages#privacy', via: 'get'

  match '/terms', to: 'pages#terms', via: 'get'

  match '/about', to: 'pages#about', via: 'get'

  match '/guestbook', to: 'problems#index', via: 'get'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :forum
  
  validates :reply, presence: true
  validates :user_id, presence: true
  validates :forum_id, presence: true

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  has_many :comments, dependent: :destroy
  
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :content, presence: true

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :vote_options, dependent: :destroy
  validates :topic, presence: true

  accepts_nested_attributes_for :vote_options, reject_if: :all_blank, allow_destroy: true

  def normalized_votes_for(option)
    votes_summary == 0? 0 : (option.votes.count.to_f / votes_summary) * 100 
  end

  def votes_summary
    vote_options.inject(0) { |summary, option| summary + option.votes.count }
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base

  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :doubt, presence: true

end

app/models/qna.rb
class Qna < ActiveRecord::Base

  valid_email_exp = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :mail, presence: true, format: { with: valid_email_exp }
  validates :ques, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes
  has_many :problems, dependent: :destroy
  has_many :comments, dependent: :destroy

  def voted_for?(poll)
    votes.any? { |v| v.vote_option.poll == poll }
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :vote_option
  counter_culture :vote_option
end

app/models/vote_option.rb
class VoteOption < ActiveRecord::Base
  belongs_to :poll
  validates :title, presence: true
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  before_action :admin_user, except: [:index, :show]

  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @comments = @forum.comments.order('created_at DESC')

  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      flash[:success] = 'Forum was created'
      redirect_to @forum
    else
      render 'new'
    end
  end

  def destroy
  end

  private

    def forum_params
      params.require(:forum).permit(:title, :content)
    end

    def admin_user
      redirect_to (forums_url) unless current_user.admin?
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def privacy
  end

  def terms
  end

  def about
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  def show
    @poll = Poll.includes(:vote_options).find_by_id(params[:id])
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    if @poll.save
      redirect_to @poll
      flash[:success]= 'Poll was successfully created.'
      else
        render 'new'
      end
  end


  def edit
    @poll = Poll.find_by_id(params[:id])
  end

  def update
    @poll = Poll.find_by_id(params[:id])
    if @poll.update_attributes(poll_params)
      flash[:success] = 'Poll was updated'
      redirect_to @poll
    else
      render 'edit'
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    flash[:success] =  'Poll was successfully deleted.'
    redirect_to polls_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:topic, vote_options_attributes: [:id, :title, :_destroy])
    end
end

app/controllers/qnas_controller.rb
class QnasController < ApplicationController
  # before_action :set_qna, only: [:show, :edit, :update, :destroy]

  # GET /qnas
  # GET /qnas.json

  # GET /qnas/1
  # GET /qnas/1.json

  # GET /qnas/new
  def new
    @qna = Qna.new
  end

  # GET /qnas/1/edit

  # POST /qnas
  # POST /qnas.json
  def create
    @qna = Qna.new(qna_params)

    if @qna.save
      flash[:success] = 'Question was successfully created.' 
      redirect_to root_url 
    else
      render 'new'
    end
  end

  # PATCH/PUT /qnas/1
  # PATCH/PUT /qnas/1.json

  # DELETE /qnas/1
  # DELETE /qnas/1.json

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qna
      @qna = Qna.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qna_params
      params.require(:qna).permit(:ques, :mail)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def create

    if current_user && params[:poll] && params[:poll][:id] && params[:vote_option] && params[:vote_option][:id]
      @poll = Poll.find_by_id(params[:poll][:id])
      @option = @poll.vote_options.find_by_id(params[:vote_option][:id])
      if @option && @poll && !current_user.voted_for?(@poll)
        @option.votes.create({ user_id: current_user.id })
      else
        render js: 'alert(\'Your vote cannot be saved. Have you already voted.\');'
      end
    else
      render js: 'alert(\'Your vote cannot be saved.\')'
    end
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper

  def visualize_votes_for(option)

    content_tag :div, class: 'progress' do
      content_tag :div, class: 'progress-bar', style: "width: #{option.poll.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end

  end

end

app/helpers/qnas_helper.rb
module QnasHelper
end

app/helpers/vote_options_helper.rb
module VoteOptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Opinia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'Opinia', root_path, class: 'navbar-brand' %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Polls', polls_path %></li>
        <li><%= link_to 'Guestbook', guestbook_path %></li>
        <li><%= link_to 'Forums', forums_path %></li>
        <li><%= link_to 'Q & A', new_qna_path %></li>
      </ul>
      <ul class="user navbar-nav" style="float:right">
        <% if current_user %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="container">
    <div class="inside">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
  </div>
  <div class = "footer">
    <nav class = "nav-footer">
      <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Terms & Conditions", terms_path %></li>
        <li><%= link_to "Privacy Policy", privacy_path %></li>
      </ul>
    </nav>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1 id="about_head">MANIA Opinia V1.0</h1>
<h6 id="about_tagline">A venture of Mania Technologies</h6>
<div class="my-content">
  <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspOpinia is one of the ventures of Mania Technologies which is a dream project of its founders. There is only one aim to Mania and that is to stand on the top of the world of Computing.</p>
  <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspOpinia is an idea developed in the mind of a group of students who was supposed to do their Main-Project necessary for the completion of the final year of Bachelor's degree in computer science and engineering. The group decided to use a new programming language which is perfect for web development. Thus they ended up with Ruby on Rails or simply Rails. Then with the previous experience of building a social site for mini-project they developed Opinia. </p>
  <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspThey decided to use an idea to empower citizens in running a country as a base to build this project. Basically Opinia is a community engagement platform which can be customized to help the citizens in running their own country.</p>
  <p id="about_thanks">Thanks for visiting Opinia.</p>
</div>

app/views/pages/home.html.erb
<h1>A complete community solution</h1>
<div class='home'>
  <h3>Fill with the content of the community</h3>
</div>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_comment_form.html.erb
<%= form_for(current_user.comments.build(forum_id: @forum.id)) do |f| %>
  <%= render 'shared/errors', object: f.object %>
  <div class="form-group">
    <%= f.text_area :reply, class: 'form-control' %>
  </div>
  <%= f.hidden_field :forum_id %>

  <div class="action">
    <%= f.submit 'Post comment', class: 'btn btn-primary align-right' %>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-warning">
    <h4>The following errors were found:</h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>